config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get 'forget', to: 'users/passwords#forget'
    patch 'update_password', to: 'users/passwords#update_password'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :medical_subjects, :only => [:index]
  resources :medical_drafts do
    get :organize, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :websites do
    resources :documents do
      get :check, :on => :member
      get :download, :on => :member
      get :preview, :on => :member
    end
    resources :pages do
      get :set_parent, :on => :collection
    end
    get :export, :on => :member
  end

  resources :newsites do
    get :draft_navbar, :on => :member
    get :draft_edit, :on => :member
    put :draft_update, :on => :member
    patch :draft_update, :on => :member
    get :produce, :on => :member
    get :prepare, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end

  resources :subunits

  resources :color_libraries
  resources :icon_libraries

  resources :navbars
  resources :formats
  resources :blocks
  resources :block_contents
  resources :carousels
  resources :title_ones
  resources :title_twos
  resources :title_threes

  resources :statistics, :only => [:index] do
    get :line, :on => :collection
    get :series, :on => :collection
    get :column, :on => :collection
    get :pie, :on => :collection
    get :bar, :on => :collection
    get :area, :on => :collection
    get :scatter, :on => :collection
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors

  root :to => 'home#index'
end

app/models/image_library.rb
# == Schema Information
#
# Table name: image_libraries
#
#  id         :integer          not null, primary key
#  category   :string           default(""), not null
#  style      :string           default(""), not null
#  file_name  :string           default(""), not null
#  tag        :string           default(""), not null
#  width      :float            default(0.0), not null
#  height     :float            default(0.0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ImageLibrary < ActiveRecord::Base
  #searchkick

end

app/controllers/image_libraries_controller.rb
class ImageLibrariesController < ApplicationController
  layout "application_control"
  before_filter :authenticate_user!
  load_and_authorize_resource

   
  def index
    @image_libraries = ImageLibrary.all
  end
   

   
  def show
    @image_library = ImageLibrary.find(params[:id])
  end
   

   
  def new
    @image_library = ImageLibrary.new
    
  end
   

   
  def create
    @image_library = ImageLibrary.new(image_library_params)
    #@image_library.user = current_user
    if @image_library.save
      redirect_to @image_library
    else
      render :new
    end
  end
   

   
  def edit
    @image_library = ImageLibrary.find(params[:id])
  end
   

   
  def update
    @image_library = ImageLibrary.find(params[:id])
    if @image_library.update(image_library_params)
      redirect_to image_library_path(@image_library) 
    else
      render :edit
    end
  end
   

   
  def destroy
    @image_library = ImageLibrary.find(params[:id])
    @image_library.destroy
    redirect_to :action => :index
  end
   

  private
    def image_library_params
      params.require(:image_library).permit( :category, :style, :file_name, :width, :height, :tag)
    end
  
  
end

app/views/image_libraries/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for @image_library do |f|
        - if @image_library.errors.any?
          #error_explanation
            %h2= "#{pluralize(@image_library.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @image_library.errors.full_messages.each do |msg|
                %li= msg
      
        .form-group.row
          = f.label Setting.image_libraries.category, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :category, :class => "form-control"
          
        .form-group.row
          = f.label Setting.image_libraries.style, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :style, :class => "form-control"
          
        .form-group.row
          = f.label Setting.image_libraries.file_name, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :file_name, :class => "form-control"
          
        .form-group.row
          = f.label Setting.image_libraries.width, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.number_field :width, :class => "form-control"
          
        .form-group.row
          = f.label Setting.image_libraries.height, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.number_field :height, :class => "form-control"
          
        .form-group.row
          = f.label Setting.image_libraries.tag, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_area :tag, :class => "form-control", :rows => "20"
          
      
      
        .form-group.row
          .col-sm-3.offset-sm-2
            = f.submit '保存', :class => "btn btn-success"
          .col-sm-3.offset-sm-1
            = link_to '返回', image_libraries_path, :class => "btn btn-danger"

app/views/image_libraries/edit.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/image_libraries/index.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid.p-0
    .row
      .col-md-12
        %table.text-center.table-bordered.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :"data-search" => "true",:'data-advanced-search'=>"true", :'data-id-table'=>"advancedTable"}
          %thead.thead-light
            %tr
              %th{:scope => "col"} #
            
              %th{:scope => "col"}
                = Setting.image_libraries.category
              %th{:scope => "col"}
                = Setting.image_libraries.style
              %th{:scope => "col"}
                = Setting.image_libraries.file_name
              %th{:scope => "col"}
                = Setting.image_libraries.width
              %th{:scope => "col"}
                = Setting.image_libraries.height
              %th{:scope => "col"}
                = Setting.image_libraries.tag
              %th{:scope => "col"}
          %tbody
            - @image_libraries.each_with_index do |image_library, index|
              %tr
                %td{:scope => "row"}
                  = index+1
              
                %td
                  = image_library.category
                %td
                  = image_library.style
                %td
                  = image_library.file_name
                %td
                  = image_library.width
                %td
                  = image_library.height
                %td
                  = image_library.tag
                %td
                  .container-fluid
                    .row
                      = link_to image_library_path(image_library), :class => "text-info col" do
                        = fa_icon "search"
                      = link_to edit_image_library_path(image_library), :class => "text-success col" do
                        = fa_icon "edit"
                      = link_to image_library, :method => :delete, :data => {:confirm => "确定删除吗?"}, :class => "text-danger col" do
                        = fa_icon "trash"

= render "layouts/control_panel"

app/views/image_libraries/show.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid
    .row
      .col-md-12
        %table.table.text-center.table-bordered
          %thead
            %tr
            
              %th 
                = Setting.image_libraries.category
              %th 
                = Setting.image_libraries.style
              %th 
                = Setting.image_libraries.file_name
              %th 
                = Setting.image_libraries.width
              %th 
                = Setting.image_libraries.height
              %th 
                = Setting.image_libraries.tag
          %tbody
            %tr
            
              %td
                = @image_library.category
              %td
                = @image_library.style
              %td
                = @image_library.file_name
              %td
                = @image_library.width
              %td
                = @image_library.height
              %td
                = @image_library.tag
    

= render "layouts/control_panel"