config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get 'forget', to: 'users/passwords#forget'
    patch 'update_password', to: 'users/passwords#update_password'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :medical_subjects, :only => [:index]
  resources :medical_drafts do
    get :organize, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :websites do
    resources :documents do
      get :check, :on => :member
      get :download, :on => :member
      get :preview, :on => :member
    end
    resources :pages do
      get :set_parent, :on => :collection
    end
    get :export, :on => :member
  end

  resources :newsites do
    get :draft_navbar, :on => :member
    get :draft_edit, :on => :member
    put :draft_update, :on => :member
    patch :draft_update, :on => :member
    get :produce, :on => :member
    get :prepare, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end

  resources :subunits

  resources :color_libraries
  resources :icon_libraries

  resources :navbars
  resources :formats
  resources :blocks
  resources :block_contents
  resources :carousels
  resources :title_ones
  resources :title_twos
  resources :title_threes

  resources :statistics, :only => [:index] do
    get :line, :on => :collection
    get :series, :on => :collection
    get :column, :on => :collection
    get :pie, :on => :collection
    get :bar, :on => :collection
    get :area, :on => :collection
    get :scatter, :on => :collection
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors

  root :to => 'home#index'
end

app/models/document.rb
class Document < ActiveRecord::Base


  belongs_to :website

  validates :status, :presence => true,
                     :numericality => {:only_integer => true}

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  layout "application_control"
  before_filter :authenticate_user!
  #load_and_authorize_resource

   
  def index
    @website = Website.find(params[:website_id])
    @documents = @website.documents
  end
   
   
  def show
    @website = Website.find(params[:website_id])
    documents = @website.documents
    @document_id = params[:id].to_i
    if @document_id >= 0 and @document_id <= documents.size-1
      @document = documents[@document_id]
      gon.websiteId = @website.id
      gon.documentId = @document_id
      gon.documentStatus = @document.status
    else
      redirect_to website_documents_path(@website)
    end
  end
   
  def download
    @website = Website.find(params[:website_id])
    documents = @website.documents
    @document_id = params[:id].to_i
    @document = documents[@document_id]
    if @document
      if params[:ft] == "html"
        send_file File.join(Rails.root, "public", "websites",  @document.html_link), :filename => @website.name + "网站", :type => "application/force-download", :x_sendfile=>true
      elsif params[:ft] == "erb"
        send_file File.join(Rails.root, "public", "erb_templates",  @document.erb_link), :filename => @website.name + "网站模板", :type => "application/force-download", :x_sendfile=>true
      else
        redirect_to website_document_path(@website, @document_id)
      end
    else
      redirect_to website_document_path(@website, @document_id)
    end
  end

  def check
    @website = Website.find(params[:website_id])
    @document_id = params[:id].to_i
    @document = @website.documents[@document_id]
    respond_to do |format|
      format.json{ render :json => 
        {
          :id=>@document_id,
          :title=>@document.title,
          :status=>@document.status
        }.to_json}
    end
  end

  private
    def document_params
      params.require(:document).permit( :title)
    end
  
  
end

app/views/documents/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for @document do |f|
        - if @document.errors.any?
          #error_explanation
            %h2= "#{pluralize(@document.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @document.errors.full_messages.each do |msg|
                %li= msg
      
        .form-group.row
          = f.label Setting.documents.title, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :title, :class => "form-control"
          
        .form-group.row
          = f.label Setting.documents.erb_link, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :erb_link, :class => "form-control"
          
        .form-group.row
          = f.label Setting.documents.html_link, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :html_link, :class => "form-control"
          
        .form-group.row
          = f.label Setting.documents.status, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.number_field :status, :class => "form-control"
          
      
      
        .form-group.row
          .col-sm-3.offset-sm-2
            = f.submit '保存', :class => "btn btn-success"
          .col-sm-3.offset-sm-1
            = link_to '返回', documents_path, :class => "btn btn-danger"

app/views/documents/edit.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/documents/index.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      .card.shadow.rounded-0.mb-3
        .card-header.bg-info.text-white.rounded-0
          %h5
            = link_to websites_path, :class => "button button-border button-rounded button-caution pull-right  bg-white" do
              = fa_icon " chevron-left", text: Setting.systems.btn_back, right: false 
        .card-body
          .container-fluid
            .row
              .col-md-12
                %table.text-center.table-bordered.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :"data-search" => "true",:'data-advanced-search'=>"true", :'data-id-table'=>"advancedTable"}
                  %thead.thead-light
                    %tr
                      %th{:scope => "col"} #
                    
                      %th{:scope => "col"}
                        = Setting.documents.title
                      %th{:scope => "col"}
                        = Setting.documents.erb_link
                      %th{:scope => "col"}
                        = Setting.documents.html_link
                      %th{:scope => "col"}
                        = Setting.documents.status
                      %th{:scope => "col"}
                  %tbody
                    - @documents.each_with_index do |document, index|
                      %tr
                        %td{:scope => "row"}
                          = index+1
                      
                        %td
                          = document.title
                        %td
                          = document.erb_link
                        %td
                          = document.html_link
                        %td
                          = document.status
                        %td
                          .container-fluid
                            .row
                              = link_to website_document_path(@website, index), :class => "text-info col" do
                                = fa_icon "search"

app/views/documents/show.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      .card.shadow.rounded-0.mb-3
        .card-header.bg-info.text-white.rounded-0
          %h5
            = link_to website_documents_path, :class => "button button-border button-rounded button-caution pull-right  bg-white" do
              = fa_icon " chevron-left", text: Setting.systems.btn_back, right: false 
        .card-body
          .container-fluid
            .row
              #document_link.col-md-12
                .repalce_content
              #document_status.col-md-12
                .repalce_content
                  - if @document.status == Setting.documents.status_none or @document.status == Setting.documents.status_process
                    .gearbox.mx-auto
                      .gear.one
                        .gear-inner
                          .bar
                          .bar
                          .bar
                      .gear.two
                        .gear-inner
                          .bar
                          .bar
                          .bar
                      .gear.three
                        .gear-inner
                          .bar
                          .bar
                          .bar
                      .gear.four.large
                        .gear-inner
                          .bar
                          .ba.r
                          .bar
                          .bar
                          .bar
                          .bar
                    %h3
                      天启正在处理版本:
                      = @document.title
                  -elsif @document.status == Setting.documents.status_success
                    %table.table.text-center.table-bordered
                      %thead
                        %tr
                        
                          %th 
                            = Setting.documents.title
                          %th 
                            = Setting.documents.erb_link
                          %th 
                            = Setting.documents.html_link
                          %th 
                            = Setting.documents.status
                          %th 
                      %tbody
                        %tr
                        
                          %td
                            = @document.title
                          %td
                            = @document.erb_link
                          %td
                            = @document.html_link
                          %td
                            = @document.status
                          %td
                            = link_to '下载', download_website_document_path(@website, @document_id, :ft => 'html')
                            = link_to '预览', "/websites/" + File.basename(@document.html_link, ".zip") + "/shouye.html?previewer", :target => "_blank"
                  -else @document.status == Setting.documents.status_fail
                    %h3
                      生成失败,请联系客服