config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get 'forget', to: 'users/passwords#forget'
    patch 'update_password', to: 'users/passwords#update_password'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :medical_subjects, :only => [:index]
  resources :medical_drafts do
    get :organize, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :websites do
    resources :documents do
      get :check, :on => :member
      get :download, :on => :member
      get :preview, :on => :member
    end
    resources :pages do
      get :set_parent, :on => :collection
    end
    get :export, :on => :member
  end

  resources :newsites do
    get :draft_navbar, :on => :member
    get :draft_edit, :on => :member
    put :draft_update, :on => :member
    patch :draft_update, :on => :member
    get :produce, :on => :member
    get :prepare, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end

  resources :subunits

  resources :color_libraries
  resources :icon_libraries

  resources :navbars
  resources :formats
  resources :blocks
  resources :block_contents
  resources :carousels
  resources :title_ones
  resources :title_twos
  resources :title_threes

  resources :statistics, :only => [:index] do
    get :line, :on => :collection
    get :series, :on => :collection
    get :column, :on => :collection
    get :pie, :on => :collection
    get :bar, :on => :collection
    get :area, :on => :collection
    get :scatter, :on => :collection
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors

  root :to => 'home#index'
end

app/models/navbar.rb
# == Schema Information
#
# Table name: navbars
#
#  id         :integer          not null, primary key
#  name       :string           default(""), not null
#  website_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Navbar < ActiveRecord::Base


  has_many :menus, :dependent => :destroy
  accepts_nested_attributes_for :menus, reject_if: :all_blank, allow_destroy: true


  belongs_to :website


end

app/controllers/navbars_controller.rb
class NavbarsController < ApplicationController
  layout "application_control"
  #before_filter :authenticate_user!
  #load_and_authorize_resource

   
  def index
    @navbars = Navbar.all
  end
   

   
  def show
    @navbar = Navbar.find(params[:id])
  end
   

   
  def new
    @navbar = Navbar.new
    
    @navbar.menus.build
    
  end
   

   
  def create
    @navbar = Navbar.new(navbar_params)
    #@navbar.user = current_user
    if @navbar.save
      redirect_to @navbar
    else
      render :new
    end
  end
   

   
  def edit
    @navbar = Navbar.find(params[:id])
  end
   

   
  def update
    @navbar = Navbar.find(params[:id])
    if @navbar.update(navbar_params)
      redirect_to navbar_path(@navbar) 
    else
      render :edit
    end
  end
   

   
  def destroy
    @navbar = Navbar.find(params[:id])
    @navbar.destroy
    redirect_to :action => :index
  end
   

  private
    def navbar_params
      params.require(:navbar).permit( :name, menus_attributes: menu_params)
    end
  
  
    def menu_params
      [:id]
    end
  
end

app/views/navbars/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for @navbar do |f|
        - if @navbar.errors.any?
          #error_explanation
            %h2= "#{pluralize(@navbar.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @navbar.errors.full_messages.each do |msg|
                %li= msg
      
        .form-group.row
          = f.label Setting.navbars.name, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :name, :class => "form-control"
          
      
      
        .form-group.row
          = f.label "关联对象", :class => "col-sm-1 control-label"
          .col-sm-11
            = f.fields_for :menus do |menu|
              = render 'menu_fields', f: menu 
            .links
              = link_to_add_association "添加", f, :menus, :class => "btn btn-success"
      
        .form-group.row
          .col-sm-3.offset-sm-2
            = f.submit '保存', :class => "btn btn-success"
          .col-sm-3.offset-sm-1
            = link_to '返回', navbars_path, :class => "btn btn-danger"

app/views/navbars/_menu_fields.html.haml
.nested-fields
  .form-group
    .field.d-inline
    = link_to_remove_association "删除", f, :class => "btn btn-danger btn-sm d-inline"

app/views/navbars/edit.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/navbars/index.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid.p-0
    .row
      .col-md-12
        %table.text-center.table-bordered.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :"data-search" => "true",:'data-advanced-search'=>"true", :'data-id-table'=>"advancedTable"}
          %thead.thead-light
            %tr
              %th{:scope => "col"} #
            
              %th{:scope => "col"}
                = Setting.navbars.name
              %th{:scope => "col"}
          %tbody
            - @navbars.each_with_index do |navbar, index|
              %tr
                %td{:scope => "row"}
                  = index+1
              
                %td
                  = navbar.name
                %td
                  .container-fluid
                    .row
                      = link_to navbar_path(navbar), :class => "text-info col" do
                        = fa_icon "search"
                      = link_to edit_navbar_path(navbar), :class => "text-success col" do
                        = fa_icon "edit"
                      = link_to navbar, :method => :delete, :data => {:confirm => "确定删除吗?"}, :class => "text-danger col" do
                        = fa_icon "trash"

= render "layouts/control_panel"

app/views/navbars/show.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid
    .row
      .col-md-12
        %table.table.text-center.table-bordered
          %thead
            %tr
            
              %th 
                = Setting.navbars.name
          %tbody
            %tr
            
              %td
                = @navbar.name
    

= render "layouts/control_panel"